version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: iqroku-postgres
    environment:
      POSTGRES_USER: iqroku
      POSTGRES_PASSWORD: iqroku123
      POSTGRES_DB: iqroku_db
    ports:
      - "5433:5432"
    volumes:
      - iqroku_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iqroku -d iqroku_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  iqroku_pgdata:
